title: EA Sheffield
author: Last updated September 2024
description: >-
  Welcome to EA Sheffield, a local city group for anyone interested in figuring out how to do the most good!
baseurl: ""
url: "https://ea-sheffield.github.io"

theme: minima
plugins:
header_pages:
 - calendar.md
 - ea.md
 - contact.md